name: Service2 workflow

on:
  push:
    paths:
      - "service2/**"

jobs:
  build-service2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Run npm install
        working-directory: ./service2
        run: npm install
      - name: Run npm build
        working-directory: ./service2
        run: npm run build --if-present
      - name: Run npm test
        working-directory: ./service2
        run: npm test
        env:
          CI: true
